List<String> biodata = [
  'Hello! Im Sophia, a travel blogger with a passion for exploring new cultures and destinations. Ive been to over 30 countries and am always planning my next trip. I love meeting new people, trying exotic foods, and immersing myself in different cultures. If you have a sense of adventure and a love for travel, lets explore the world together!',
  'Hi, Im Liam! Im a wildlife photographer with a deep love for animals and nature. My job takes me to some of the most beautiful and remote places on Earth, where I get to capture the beauty of wildlife through my lens. Im looking for someone who shares my passion for animals and the great outdoors. Let\'s embark on a wild journey together!',
  'Hi, I\'m Ryan! I\'m a game developer who loves all things tech and gaming. When I\'m not developing the next big game, I\'m either playing video games, building custom PCs, or geeking out over the latest tech trends. If you\'re into gaming and tech, let\'s team up and conquer the digital world together!',
  'Hey! I\'m Mia, a personal trainer who lives and breathes fitness. I believe in living a healthy and active lifestyle, and I\'m always up for a good workout, whether it\'s at the gym, on the beach, or in a yoga studio. I\'m looking for someone who shares my passion for fitness and healthy living. Let\'s motivate each other to be our best selves!',
  'Hello! I\'m Jake, a chef with a love for all things culinary. Cooking is my art, and I enjoy experimenting with new recipes and flavors. When I\'m not in the kitchen, I love curling up with a good book or binge-watching the latest series. I\'m looking for someone who appreciates good food and cozy nights in. Let\'s share a meal and get to know each other!',
  'Hi, I\'m Emma! I\'m a graphic designer with a passion for all things creative. Whether it\'s painting, photography, or designing digital art, I\'m always looking for new ways to express myself. I love spending my free time in art galleries, cozy coffee shops, or at live music venues. If you\'re into creativity and self-expression, let\'s connect and make some beautiful memories together!',
  'Hey there! I\'m Alex, a software engineer by day and an adventure junkie by the weekend. When I\'m not coding, you can find me hiking up the Rockies, camping under the stars, or kayaking down a wild river. I live for the thrill of the great outdoors and am always looking for my next adventure. Let\'s get out there and explore the world together!'
];
