// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ-AH1ZPVxppZAdSSxHCjoNXhQOyjTQ3M',
    appId: '1:886844119186:web:c601a4ad314d510aa8ee4b',
    messagingSenderId: '886844119186',
    projectId: 'meramaahi-7bec9',
    authDomain: 'meramaahi-7bec9.firebaseapp.com',
    storageBucket: 'meramaahi-7bec9.appspot.com',
    measurementId: 'G-JN7CHVL4YM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeML76lCXZESzaqIAUbuIzTFSjDH8OwVc',
    appId: '1:886844119186:android:d19f9d77f1fe79c9a8ee4b',
    messagingSenderId: '886844119186',
    projectId: 'meramaahi-7bec9',
    storageBucket: 'meramaahi-7bec9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWMjSSz02leeewpeX7eRBRuKYAuFy9-rs',
    appId: '1:886844119186:ios:e1b8ac24e6c8f394a8ee4b',
    messagingSenderId: '886844119186',
    projectId: 'meramaahi-7bec9',
    storageBucket: 'meramaahi-7bec9.appspot.com',
    iosBundleId: 'com.example.mereMaahiDummy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWMjSSz02leeewpeX7eRBRuKYAuFy9-rs',
    appId: '1:886844119186:ios:e1b8ac24e6c8f394a8ee4b',
    messagingSenderId: '886844119186',
    projectId: 'meramaahi-7bec9',
    storageBucket: 'meramaahi-7bec9.appspot.com',
    iosBundleId: 'com.example.mereMaahiDummy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZ-AH1ZPVxppZAdSSxHCjoNXhQOyjTQ3M',
    appId: '1:886844119186:web:ad407aa88eef6810a8ee4b',
    messagingSenderId: '886844119186',
    projectId: 'meramaahi-7bec9',
    authDomain: 'meramaahi-7bec9.firebaseapp.com',
    storageBucket: 'meramaahi-7bec9.appspot.com',
    measurementId: 'G-2FHX6JDQHK',
  );
}
